name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Ustanovka zavisimostei
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Start tests
        run: |
          source venv/bin/activate
          PYTHONPATH=$(pwd) pytest

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Joining and deploying
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 10.0.2.15
          username: admin
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/Prac6
            git pull origin main
            docker-compose down
            docker-compose up --build -d
