name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Ustanovka zavisimostei
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Start tests
        run: |
          source venv/bin/activate
          PYTHONPATH=$(pwd) pytest
